### ISSUE TITLE
Support `rlang` messages in pattern of `expect_error()`

### ISSUE THREAD

**Issue by etiennebacher** [markvanderloo/tinytest#121]
Hello, the `pattern` argument of `expect_error()` doesn't work with `rlang` errors:

``` r
library(tinytest)
packageVersion("tinytest")
#> [1] '1.4.1'

foo <- function() dplyr::select(iris, var)
foo()
#> Error in `dplyr::select()`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `var` doesn't exist.
#> Backtrace: [CUT]

expect_error(foo(), "Can't subset")
#> ----- FAILED[xcpt]: <-->
#>  call| expect_error(foo(), "Can't subset")
#>  diff| The error message:
#>  diff| ''
#>  diff| does not match pattern 'Can't subset'
```

It would be possible to support this class of errors by adding this at the beginning of `expect_error()`:
```r
if (inherits(e, "rlang_error")) {
    error_message <- paste(capture.output(print(e)), collapse = "\n")
} else {
    error_message <- e$message
}
```
and by replacing subsequent `e$message` by `error_message`. Is it something you'd be willing to add? 

Happy to PR if needed. Thanks

----

Related: https://github.com/vincentarelbundock/tinysnapshot/issues/12

**Comment by markvanderloo** [comment]
Hi there, I never used `rlang`, so I am not familiar with it at all. It seems a pity that it uses a different interface for accessing the condition message. Besides `error` conditions, we would probably also need to support other types of conditions (`warning` and `message` and perhaps more?). I would rather not add `rlang`-specific code to the package, because the interface might change, and who knows what other conditioning packages will appear. I'll have a look if working with `conditionMessage()` solves the problem.

**Comment by markvanderloo** [comment]
Ok, I replaced all occurrences of `<x>$message` with `conditionMessage(<x>)`. Also, I get this:

```r
> library(rlang)
> e <- error_cnd(message="foo")
> 
> 
> conditionMessage(e)
[1] "foo"
```

**Comment by etiennebacher** [comment]
Awesome, thanks
