### ISSUE TITLE
Consider a GPL-2 | GPL-3 license?

### ISSUE THREAD

**Issue by JohnMount** [markvanderloo/tinytest#23]
I was wondering if you would consider changing the license to "GPL-2 | GPL-3"?  

This would make `tinytest` appear more compatible with `R` packages that have declared `GPL-2` only.  My thinking on this is `R` itself is "GPL-2 | GPL-3" ([ref](https://www.r-project.org/Licenses/) so in some sense any package that declares only one of GPL-2/3 is a bit more restrictive than `R` itself.

**Comment by markvanderloo** [comment]
I'm not sure what the benefits would be. For me it would make the license structure more complicated (what does GPL 2|3 even mean?). AFAICT any R package can suggest, import, depend or enhance tinytest without problems because they are not redistributing it. So if there are no real limitations to users: I'm incline to leave it the way it is.

Completely aside: has _any_ of this ever been tested in court? I never read anything but non-expert opinions on mailinglists and _all_ discussions end with: ask a lawyer. Not that it matters: if some big $$$ company wants to sue a FOSS developer for patent infringement, or said company abuses a FOSS dev's licence: you don't stand a chance anyway because of the vast difference in resources.

**Comment by JohnMount** [comment]
The benefit (if any) would be very small: someone that prefers GPL-2 to GPL-3 would be happier.  Of course there are always going be people who prefer X to Y, so there is no way to please them all. I agree: I don't think most users trigger the redistribution clauses, so those parts of the licenses are likely not in force anyway (hence there should not be issues on compatibility between GPL-2 and GPL-3 for those users).

My understanding of what "GPL-2 | GPL-3" or "GPL>=2" would mean is: the user can decide which way they feel they received the package.  

My current thinking is: in R use GPL-3 if you prefer GPL-3 to GPL-2.  If you don't wish to express a preference use "GPL-2 | GPL-3" as that is closer to R's license itself (so you are not expressing a preference if you don't want to).  Any "more permissive" license is fairly pointless as there are so many GPL-2 and GPL-3 components in most R installs/distributions.
