### ISSUE TITLE
R CMD check freezes when a test contains parallel calls

### ISSUE THREAD

**Issue by gvegayon** [markvanderloo/tinytest#36]
I've been trying to switch some of my R packages to the tinytest framework. In some of them, I use the parallel package, i.e. `parallel::makeCluster()` and that doesn't seem to work with `tinytest`. To show this, I've created a small toy package with a single function: `hello_parallel`, which creates a cluster object `cl` and calls `parallel::clusterEvalQ(cl, "hello")`. Running `tinytest::test_all` works fine, but `R CMD check` freezes.

Here is the repo where I put the toy package:

https://github.com/USCbiostats/tinytesttest

Here is one example of tinytest failing (freezing) during `R CMD check`:

https://travis-ci.org/USCbiostats/tinytesttest/builds/584236824#L728

I had to stop this build after 9 minutes running.

Also, a similar issue happens when I call R using system calls, e.g. `system2("R", ...)`.

**Comment by markvanderloo** [comment]
Thanks, I've now confirmed this locally. Bit of a riddle at the moment, I have to dig through some documentation to see where this comes from. Also, big thanks for setting up the test package.

**Comment by markvanderloo** [comment]
Ok it seems to be similar to this  [issue in testthat](https://github.com/r-lib/testthat/issues/86). I managed to avoid the trouble by setting

```
Sys.setenv("R_TESTS"="")
```
in the beginning of the test file.

Note: you do not need to unset the envvar at the end because tinytest does this automatically for you after running the test file (so `R_TESTS` only has a different value from the original one while this particular file runs).

It is a hack and a workaround but maybe you can now at least keep working while I look for a real solution.

**Comment by gvegayon** [comment]
Yes, that seems to work fine. Thanks!

**Comment by markvanderloo** [comment]
Fixed, tested with `tinytesttest`, also affects #37 https://github.com/markvanderloo/tinytest/commit/0ab06593a51029a44a644c46f890fd424302077c

**Comment by gvegayon** [comment]
Awesome, thanks!
