### ISSUE TITLE
Only last expect_true is evaluated, or at least, printed

### ISSUE THREAD

**Issue by bryanhanson** [markvanderloo/tinytest#43]
Was surprised by this while testing a package, here is a MWE:

```

# All this is running interactively
# Works as expected
library("MASS") # contains built-in data set called abbey
expect_true(length(abbey) == 31L)
expect_true(max(abbey) == 125.0)

# Now detach MASS
detach(package:MASS, unload = TRUE)

# Only the last expect_true triggers action inside this particular condition
if (requireNamespace("MASS")) {
  library("MASS")
  expect_true(max(abbey) == 125.0) # true
  expect_true(max(abbey) == 0.0) # false, but not noticed
  expect_true(length(abbey) == 31L) # true
}

```
Only the last `expect_true` is printed, and I think it is the only one evaluated.

I don't think this is the desired behavior.

**Comment by markvanderloo** [comment]
This is not a `tinytest` problem, but an R feature. Try this:

```r
if (TRUE){
  TRUE
  FALSE
  TRUE
}
```
You'll see that you get exactly one answer (the last `TRUE`). The reason is that unlike in many other languages, in `R`, `if` is a _function_. The return value is the result of the last expression. So you can do cool things like this:

```r
can_R_compute <- if ( 1 + 1 == 2 ){
  TRUE
} else {
  FALSE
}
can_R_compute
```

To convince yourself that everything is running in the example you gave, you can explicitly print everything as follows:



```r
if (requireNamespace("MASS")) {
  library("MASS")
  print( expect_true(max(abbey) == 125.0) ) # true
  print( expect_true(max(abbey) == 0.0)  )# false, but not noticed
  print( expect_true(length(abbey) == 31L)  )# true
}
```

**Comment by bryanhanson** [comment]
Thanks Mark for the explanation, and sorry for the noise.  I thought I had tried the `print` approach but apparently I mucked it up.
