### ISSUE TITLE
0 Tests

### ISSUE THREAD

**Issue by JamesThompsonC** [markvanderloo/tinytest#60]
Thank you for the package. It's great.
I noticed that if my test file uses
tinytest::expect_true(THE TEST)

instead of 
expect_true(THE TEST)

the test does not register, i.e.
run_test_fine("./inst/tinytest/test-TEST_FILE.R") 
tinytest reports "0 Tested"

It took me a while to figure this out. 
Maybe you want to warn users.

Thanks.
Jim

**Comment by markvanderloo** [comment]
Hi Jim, 

yes, that's right. This is because of the mechanism used in the package. The `expect_*` functions are [masked locally](), and the masking is circumvented when you use the `::` notation. Sounds like an annoying experience.

I will put this somewhere upfront in the vignette. I'll also see if I can make `tinytest` throw a warning about this when it occurs.

**Comment by markvanderloo** [comment]
The development version now warns for occurrences of `tinytest:::expect`, see https://github.com/markvanderloo/tinytest/commit/6fd845c1d6fe31de6539237628fe8da5a04e01f1
